# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /blog/:title/
relative_permalinks: true

# Setup
title:            Alex Daniel
description:      'Software Developer'
location:         'San Francisco, CA'
url:              http://alexander.codes
baseurl:          /

excerpt_separator: <!--more-->

sass:
    sass_dir: _sass
